version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Zekth
  assignees:
  - Zekth
  ignore:
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.1
  - dependency-name: vue-router
    versions:
    - 3.4.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.1
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.1
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.32
